/* 貼文分類：c = 分類 id（見 categories.js），t = 主題標籤。由 scripts/classify_posts.mjs 以 AI 依內容判斷；
   可手動修改，已有的項目不會被覆蓋（除非用 --all）。獨立於 data.js，所以每日 Threads 同步不會洗掉。 */
window.POST_CATS = {
  "DeLBJFXE4ua": {"c":"news","t":["Codex"]},
  "DeJTqFhE4rx": {"c":"events","t":["Claude","Meetup"]},
  "DeB9J_ykyMT": {"c":"events","t":["GitHub","Game Dev"]},
  "DeBqSftE4lU": {"c":"tools","t":["DeepSeek","Harness"]},
  "DeBZM_nE6Ip": {"c":"events","t":["Hackathon"]},
  "Dd-l9MDFLcq": {"c":"events","t":["Hackathon","Meta"]},
  "Dd87NDGk-x9": {"c":"tools","t":["Stanford","Courses"]},
  "Dd85JZcEz44": {"c":"life","t":["Games"]},
  "Dd8XNHJE7H4": {"c":"thoughts","t":["AI Agent","Learning"]},
  "Dd21zc8E6qu": {"c":"events","t":["Hackathon","Agent"]},
  "Dd2prQcE1p5": {"c":"news","t":["NVIDIA","Agent Security"]},
  "Dd0smhtm4p4": {"c":"news","t":["ZCode","Privacy"]},
  "DdnOjx0E5kx": {"c":"news","t":["Claude","Benchmark"]},
  "Ddk1dZkkwsn": {"c":"news","t":["MiMo","Xiaomi"]},
  "Ddkdz_XGjmD": {"c":"news","t":["MiMo","Xiaomi"]},
  "Ddih8R4k6yr": {"c":"tools","t":["GLM","Free Tokens"]},
  "DdiKhwYk_rG": {"c":"news","t":["ZCode","Open Source"]},
  "Ddh_PX5k-G2": {"c":"tools","t":["Jev","Free Tokens"]},
  "Ddh1c8Ik6bq": {"c":"news","t":["Qwen","Image Gen"]},
  "DdgV7U3E2iT": {"c":"news","t":["Qwen","Image Gen"]},
  "Ddcz31oE9zP": {"c":"events","t":["Startup","VC"]},
  "DdbvPAAE3Zi": {"c":"events","t":["Startup"]},
  "Ddbk7m1k9bq": {"c":"events","t":["Education","Startup"]},
  "Ddafoylk2B4": {"c":"events","t":["MOPCON"]},
  "DdQ4jy2kz6O": {"c":"events","t":["Boba Tech","Sovereign AI"]},
  "DdQXuwpE8Kp": {"c":"events","t":["Boba Tech","Startup"]},
  "DdQSLsXk4fe": {"c":"prompts","t":["Image Prompt"]},
  "DdGwI87mwtM": {"c":"tools","t":["MiMo","Xiaomi"]},
  "DdGoP9am7YU": {"c":"events","t":["Boba Tech","Startup"]},
  "DdGjq8VGzKX": {"c":"events","t":["Boba Tech"]},
  "DdGcbrVm1gU": {"c":"events","t":["Boba Tech","OpenAI"]},
  "DdGZlDTG2wo": {"c":"prompts","t":["Image Prompt"]},
  "DdFpa-9E0rm": {"c":"events","t":["Boba Tech","AI"]},
  "DdD1E-ik_uv": {"c":"events","t":["Hackathon","Math"]},
  "Dc-5LEcE-O-": {"c":"prompts","t":["Image Prompt"]},
  "Dc5wjZ0k4NO": {"c":"tools","t":["Learning","Language"]},
  "Dc5lSrck3UP": {"c":"news","t":["GPT-6"]},
  "Dc4oHAyE_ks": {"c":"tools","t":["GLM","Free Tokens"]},
  "Dc3UHAwE4SA": {"c":"thoughts","t":["Apple","Video"]},
  "Dc2IxxrEwhu": {"c":"news","t":["GPT-6","Security"]},
  "Dczp6Amk7w7": {"c":"events","t":["Anthropic","Ambassador"]},
  "DczlIRuk-Gi": {"c":"events","t":["Claude","Ambassador"]},
  "DcmefHPE0Bb": {"c":"tools","t":["Ox Alpha","Free Tokens"]},
  "DcctWYMFO60": {"c":"events","t":["Boba Tech","Startup"]},
  "DcawHs7G_Ui": {"c":"prompts","t":["Image Prompt","Travel"]},
  "DcP4Sz4E3rL": {"c":"news","t":["OpenAI","Enterprise"]},
  "DcP4REnE6Jz": {"c":"news","t":["GLM","DeepSeek"]},
  "DcOXTaJE4__": {"c":"tools","t":["Resources","AI News"]},
  "DcNIuSik9AA": {"c":"news","t":["Claude","Gmail"]},
  "DcNHaOHk2aP": {"c":"news","t":["OpenAI","Safety"]},
  "DcCjMnemanu": {"c":"thoughts","t":["AI Education"]},
  "DcAa70NE0mS": {"c":"tools","t":["Watermark","Open Source"]},
  "Db_8Kt8E1uU": {"c":"news","t":["DeepSeek","Harness"]},
  "Db_7rADk_LX": {"c":"news","t":["DeepSeek","Benchmark"]},
  "DbnzGmdE91J": {"c":"tools","t":["Unity","CLI"]},
  "DbIyJ6nE7tf": {"c":"tools","t":["Notes","Open Source"]},
  "DbFgDgoE3V3": {"c":"tools","t":["Kimi","GitHub"]},
  "DbBEknTk7gM": {"c":"dev","t":["Claude Skill","Open Source"]},
  "DbAQJTJE8up": {"c":"events","t":["Codex","Workshop"]},
  "DZ-MAbuE4Qr": {"c":"dev","t":["Python","Education"]},
  "DZztwi6Gxfn": {"c":"dev","t":["Vibe Coding","Claude Skill"]},
  "DZpu6RvE1NU": {"c":"dev","t":["Vibe Coding","Evaluation"]},
  "DZoFMp-k6qp": {"c":"dev","t":["Vibe Coding"]},
  "DZjpDB_G9he": {"c":"dev","t":["Vibe Coding","Prompt"]},
  "DZSqkvkk8gb": {"c":"dev","t":["Education","Open Source"]}
};
